### ISSUE TITLE
Climbing ladders makes you accumulate fall damage

### ISSUE THREAD

**Issue by Gfauf** [SpearAndFang/primitive-survival#6]
Climbing long ladders makes me instantly die when I leave the ladder, like if I was accumulating fall damage.
Disabling this mod makes all the ladders I had placed disappear.
Also they are wooden ladders, made with sticks, and I was stacking them up only with a block behind every 5 Y levels.
It's a little strange, its like the ladders I put aiming at the ladder I'm currently standing on doesn't count and the ones that I had placed with a block behind them stay.

**Comment by SpearAndFang** [comment]
Are you using any other mods?  Because this doesn't sound like anything to do with Primitive Survival.  This mod does not touch ladders or players in any way - in fact it mostly just adds new content that is safely and far removed from vanilla.  Now I could see a mod like xSkills or the VSMovementMod causing such a thing.

**Comment by Gfauf** [comment]
I have these mods installed:
Acorns, CulinaryArtillery, Vsquest, Wildcraft
AnvilMetalRecovery, carryOn, Chiseltools
DJsVanillaTools, drbraziers, ExpandedFoods
FeverstoneWilds, morepiles, petai
PrimitiveSurvival, Spawnhighlight, StorageOptions
I was troubleshooting, disabling one by one the mods and the disappearing of ladders occurred when I disabled Primitive Survival, so I guess It has to do something with it, but maybe it's just impossible to troubleshoot with the amount of mods I have, as the last patch note had a change in ladders recipes I thought it may had something to do with it.

**Comment by SpearAndFang** [comment]
"last patch note had a change in ladders recipes"
I'm sorry, what are you referring to here exactly?

Based on that list of mods, carryOn is the only mod I'm aware of that mucks with player interactions.  I'll take a look at some of the others on your list that I am not familiar with and see if something else catches my eye.

**Comment by SpearAndFang** [comment]
The More Piles mod mucks with ladder behaviors...maybe that...

**Comment by Gfauf** [comment]
Oh my bad, I read it wrong, it said this:
"v3.2.9: TWEAK: modified better stairs recipes slightly so they won't conflict with mods like Slabs & Stairs (https://mods.vintagestory.at/show/mod/7887)"
It was stairs, not ladders, I was just guessing by what I had read, my bad.

**Comment by SpearAndFang** [comment]
I'm more than willing to look at your log files if it happens again or is easily re-creatable.  I think client-main.txt or the -debug.txt logs might reveal something...maybe.

**Comment by Gfauf** [comment]
Oh thank you for helping me on this, I didn't noticed that, I was searching one by one my mods to see which one could had something to do with ladders and all I could figure out was this one because I had read the patch note wrong.
I tried making a tall ladder from the ground without support with only Primitive Survival enabled, and putting a block behind me and then leaving the ladder, and nothing happened, tried with all the mods enabled and nothing happened, so I don't know how to recreate it.

Here you have my logfiles if you want to search more into it but if this mod doesn't touch ladders nor interaction with those then it must be another mod or the game itself, if you want you can close this then, thanks for the help!

[client-debug.txt](https://github.com/SpearAndFang/primitive-survival/files/12755917/client-debug.txt)
[client-main.txt](https://github.com/SpearAndFang/primitive-survival/files/12755918/client-main.txt)

**Comment by SpearAndFang** [comment]
Yeah, nothing in those logs are terribly revealing.  Other than the fact that I would love to tidy up a bunch of those other mods so they don't throw so many warnings and errors unnecessarily.  ;)

My only other suggestion is that if you have other disabled mods and they are sitting in your mods folder, then pull them out of your mods folder completely and store them somewhere else.  Then start the game again and go back into the mod manager and click reload mods.  I've seen some strange things happen with disabled mods.
